# Generated by Django 3.0.8 on 2024-06-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_auto_20200712_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='English', max_length=20),
        ),
    ]
